// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8osPjAidgS4VDagj7i2oMUyuIxqpXgc',
    appId: '1:405662165817:web:fe7969d6b50109817fd6e8',
    messagingSenderId: '405662165817',
    projectId: 'crm-by-apptriangle',
    authDomain: 'crm-by-apptriangle.firebaseapp.com',
    storageBucket: 'crm-by-apptriangle.firebasestorage.app',
    measurementId: 'G-G4TM9VPNPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrA3HxvRb1ZWSHJmEaNT0jFtsdJHTPpEo',
    appId: '1:405662165817:android:04e38fa0ae10f4b77fd6e8',
    messagingSenderId: '405662165817',
    projectId: 'crm-by-apptriangle',
    storageBucket: 'crm-by-apptriangle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJ9FIY4Ab2A-31I986yrPmQNThim9lKQ',
    appId: '1:405662165817:ios:96f59b69593e4e7b7fd6e8',
    messagingSenderId: '405662165817',
    projectId: 'crm-by-apptriangle',
    storageBucket: 'crm-by-apptriangle.firebasestorage.app',
    iosBundleId: 'com.musfiqul.crmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJ9FIY4Ab2A-31I986yrPmQNThim9lKQ',
    appId: '1:405662165817:ios:9881f2bc686472a77fd6e8',
    messagingSenderId: '405662165817',
    projectId: 'crm-by-apptriangle',
    storageBucket: 'crm-by-apptriangle.firebasestorage.app',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU8osPjAidgS4VDagj7i2oMUyuIxqpXgc',
    appId: '1:405662165817:web:ce1992a6bf60bfe17fd6e8',
    messagingSenderId: '405662165817',
    projectId: 'crm-by-apptriangle',
    authDomain: 'crm-by-apptriangle.firebaseapp.com',
    storageBucket: 'crm-by-apptriangle.firebasestorage.app',
    measurementId: 'G-Z0QWZYZ1HC',
  );
}
